# Generated by Django 4.1.7 on 2023-03-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='farmer_id',
        ),
    ]
