# Generated by Django 4.1.7 on 2023-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_username_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='crops_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=20)),
                ('soil_quality', models.CharField(max_length=20)),
                ('rainfall', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
                ('fertilizer', models.CharField(max_length=20)),
            ],
        ),
    ]
