# Generated by Django 4.1.7 on 2023-03-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_delete_crops_detail_delete_farmer_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropdetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
                ('rain', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=100)),
                ('nutrient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('citizenshipfrontpic', models.ImageField(upload_to='images/')),
                ('citizenshipbackpic', models.ImageField(upload_to='images/')),
                ('profilepic', models.ImageField(upload_to='images/')),
                ('landownerpic', models.ImageField(upload_to='images/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('companyregpic', models.ImageField(upload_to='images/')),
                ('profilepic', models.ImageField(upload_to='images/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('farmer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user_farmer')),
                ('seller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user_seller')),
            ],
        ),
    ]
