# Generated by Django 4.1.7 on 2023-03-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_farmer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user_farmer',
            name='gender',
        ),
    ]
