# Generated by Django 4.1.7 on 2023-03-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_user_farmer_dob_remove_user_farmer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='user_farmer',
            name='loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.login'),
        ),
        migrations.AddField(
            model_name='user_seller',
            name='loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.login'),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
