# Generated by Django 4.1.7 on 2023-03-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_user_farmer_loginid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_farmer',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_farmer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
