# Generated by Django 4.1.7 on 2023-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_seller',
            name='companyregpic',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='maxtemp',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='mintemp',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='rain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
