# Generated by Django 4.1.7 on 2023-05-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_farmer_seller_delete_user_farmer_delete_user_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='weatherdata',
        ),
    ]
