# Generated by Django 4.1.7 on 2023-05-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_delete_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship_back'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='citizenship_front'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='landownership',
            field=models.ImageField(blank=True, null=True, upload_to='landownership'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic'),
        ),
    ]
