# Generated by Django 4.1.7 on 2023-05-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
