# Generated by Django 4.1.7 on 2023-05-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
