# Generated by Django 4.1.7 on 2023-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_farmer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdetail',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='crops', to='login.farmer'),
        ),
    ]
