# Generated by Django 4.1.7 on 2023-05-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_cropdetail_farmers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdetail',
            name='farmers',
        ),
        migrations.AddField(
            model_name='farmer',
            name='crops',
            field=models.ManyToManyField(blank=True, null=True, to='login.cropdetail'),
        ),
    ]
