# Generated by Django 4.1.7 on 2023-05-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_cropdetail_farmers_farmer_crops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='crops',
        ),
    ]
