# Generated by Django 4.1.7 on 2023-05-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_remove_farmer_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
